# Generated by Django 5.0 on 2023-12-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Address_line_1',
            field=models.CharField(max_length=200),
        ),
    ]
