# Generated by Django 5.0 on 2023-12-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customuser_address_line_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Address_line_1',
            field=models.TextField(),
        ),
    ]
